const itemsCollection = [
    {
        name: "NIKE",
        category: "men",
        color: "red",
        type: "shoes",
        description: "Air Force Sneakers",
        price: 161,
        size: ["36", " 38", " 40"],
        highlights: ["x100% leather", " Flat rubber sole", " lace fastening", " Nike swoosh signature", " Branded insole"],
        image: [{
                fieldname: "images",
                originalname: "airforce-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661722869733.jpg",
                path: "public/men/images-1661722869733.jpg",
                size: 54700
            },
            {
                fieldname: "images",
                originalname: "airforce-2.webp",
                encoding: "7bit",
                mimetype: "image/webp",
                destination: "./public/men",
                filename: "images-1661722869795.jpg",
                path: "public/men/images-1661722869795.jpg",
                size: 57072
            },
            {
                fieldname: "images",
                originalname: "airforce-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661722869827.jpg",
                path: "public/men/images-1661722869827.jpg",
                size: 43746
            },
            {
                fieldname: "images",
                originalname: "airforce-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661722869886.jpg",
                path: "public/men/images-1661722869886.jpg",
                size: 44942
            }
        ]
    },
    {
        name: "KENZO",
        category: "men",
        color: "pen",
        type: "hoodie",
        description: "Tiger Head Hoodie",
        price: 281,
        size: ["XS", " S", " M", " L", " XL"],
        highlights: ["Dove grey", " Cotton", " Signature Tiger Hea motif", " Drawstring hood", " Long sleevs"],
        image: [{
                fieldname: "images",
                originalname: "kenzo-tiger-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661723063348.jpg",
                path: "public/men/images-1661723063348.jpg",
                size: 271017
            },
            {
                fieldname: "images",
                originalname: "kenzo-tiger-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661723063352.jpg",
                path: "public/men/images-1661723063352.jpg",
                size: 275000
            },
            {
                fieldname: "images",
                originalname: "kenzo-tiger-head-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661723063356.jpg",
                path: "public/men/images-1661723063356.jpg",
                size: 169900
            }
        ],
    },
    {
        name: "Les Tien",
        category: "men",
        color: "black",
        type: "short",
        description: "Track shorts",
        price: 237,
        size: ["XS", " S", " M", " L", " XL"],
        highlights: ["navy blue", " cotton", " press stud detailing", " elasticated waistband", " pull-on style", " turn-up hem", " two side inset pockets"],
        image: [{
                fieldname: "images",
                originalname: "les-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661723899489.jpg",
                path: "public/men/images-1661723899489.jpg",
                size: 102876
            },
            {
                fieldname: "images",
                originalname: "les-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661723899490.jpg",
                path: "public/men/images-1661723899490.jpg",
                size: 153214
            },
            {
                fieldname: "images",
                originalname: "les-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/men",
                filename: "images-1661723899493.jpg",
                path: "public/men/images-1661723899493.jpg",
                size: 44160
            }
        ],
    },
    {
        name: "Valentino",
        category: "women",
        color: "black",
        type: "jeans",
        description: "Straight-leg jeans",
        price: 1940,
        size: ["XS", " S", " M", " L", " XL"],
        highlights: ["Black", " Cotton", " Logo patch to the rear", " cropped leg", " Feather-trim detailing"],
        detail: "Crafted in a straight-leg silhouette, these black Valentino jeans are trimmed with wispy feathers at the hem for a tactile completion.",
        image: [{
                fieldname: "images",
                originalname: "valentino-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661733798343.jpg",
                path: "public/women/images-1661733798343.jpg",
                size: 100712
            },
            {
                fieldname: "images",
                originalname: "valentino-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661733798345.jpg",
                path: "public/women/images-1661733798345.jpg",
                size: 52206
            },
            {
                fieldname: "images",
                originalname: "valentino-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661733798350.jpg",
                path: "public/women/images-1661733798350.jpg",
                size: 127182
            },
            {
                fieldname: "images",
                originalname: "valentino-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661733798355.jpg",
                path: "public/women/images-1661733798355.jpg",
                size: 44712
            }
        ],
    },
    {
        name: "Balenciaga",
        category: "women",
        color: "#457199",
        type: "jacket",
        description: "Twisted-sleeve jacket",
        price: 1610,
        size: ["S", " M", " L"],
        highlights: ["Light blue", " Cotton", " Twisted detailing", " Classic collar", " Concealed front fastening", " Two chest flap pockets"],
        detail: "Crafted in a straight-leg silhouette, these black Valentino jeans are trimmed with wispy feathers at the hem for a tactile completion.",
        image: [{
                fieldname: "images",
                originalname: "balenciaga-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734130933.jpg",
                path: "public\\women\\images-1661734130933.jpg",
                size: 255238
            },
            {
                fieldname: "images",
                originalname: "balenciaga-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734131155.jpg",
                path: "public\\women\\images-1661734131155.jpg",
                size: 129700
            },
            {
                fieldname: "images",
                originalname: "balenciaga-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734131173.jpg",
                path: "public\\women\\images-1661734131173.jpg",
                size: 92536
            },
            {
                fieldname: "images",
                originalname: "balenciaga-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734131179.jpg",
                path: "public\\women\\images-1661734131179.jpg",
                size: 118522
            }
        ],
    },
    {
        name: "Amina Muadi",
        category: "women",
        color: "brown",
        type: "shoes",
        description: "Sita leather sandals",
        price: 937,
        size: ["XS", " S", " M", " L"],
        highlights: ["Brown", " Leather", " Wraparound style", " Self-tie fastening", " Transparent strap", " Platform sole"],
        detail: "Sita leather sandals",
        image: [{
                fieldname: "images",
                originalname: "amina-muaddi-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734268135.jpg",
                path: "public\\women\\images-1661734268135.jpg",
                size: 39380
            },
            {
                fieldname: "images",
                originalname: "amina-muaddi-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734268316.jpg",
                path: "public\\women\\images-1661734268316.jpg",
                size: 32366
            },
            {
                fieldname: "images",
                originalname: "amina-muaddi-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734268317.jpg",
                path: "public\\women\\images-1661734268317.jpg",
                size: 58369
            },
            {
                fieldname: "images",
                originalname: "amina-muaddi-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734268447.jpg",
                path: "public\\women\\images-1661734268447.jpg",
                size: 67466
            }
        ],
    },
    {
        name: "Palm Angels",
        category: "women",
        color: "brown",
        type: "dress",
        description: "Mini t-shirt dress",
        price: 383,
        size: ["XS", " S", " M", " L"],
        highlights: ["Snd brown", " Stretch model", " Embroidered logo at the chest", " Crew neck", " Drop shoulder", " Long sleeves"],
        detail: "Palm Angels continues to provide L.A inspired streetwear in this AW22 collection. Made from stretch-modal, this long-sleeved T-shirt dress is subtly elevated by an embroidered logo at the chest. Dropped shoulders and a batwing style add to the laid-back aesthetic.",
        image: [{
                fieldname: "images",
                originalname: "palm-angels-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734413305.jpg",
                path: "public\\women\\images-1661734413305.jpg",
                size: 110962
            },
            {
                fieldname: "images",
                originalname: "palm-angels-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734413494.jpg",
                path: "public\\women\\images-1661734413494.jpg",
                size: 39972
            },
            {
                fieldname: "images",
                originalname: "palm-angels-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734413498.jpg",
                path: "public\\women\\images-1661734413498.jpg",
                size: 39006
            },
            {
                fieldname: "images",
                originalname: "palm-angels-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734413505.jpg",
                path: "public\\women\\images-1661734413505.jpg",
                size: 128315
            }
        ],
    },
    {
        name: "Balenciaga",
        category: "women",
        color: "brown",
        type: "shoes",
        description: "Trrack-3 sneakers",
        price: 864,
        size: ["36 38 40"],
        highlights: ["Blush beige", " Knitted panels", " Panelled design", " Logo path at the tongue", " Branded heel counter", " Round toe"],
        detail: "Trrack-3 sneakers",
        image: [{
                fieldname: "images",
                originalname: "balenciaga-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734565145.jpg",
                path: "public\\women\\images-1661734565145.jpg",
                size: 71926
            },
            {
                fieldname: "images",
                originalname: "balenciaga-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734565543.jpg",
                path: "public\\women\\images-1661734565543.jpg",
                size: 59842
            },
            {
                fieldname: "images",
                originalname: "balenciaga-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734565874.jpg",
                path: "public\\women\\images-1661734565874.jpg",
                size: 58410
            },
            {
                fieldname: "images",
                originalname: "balenciaga-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734566165.jpg",
                path: "public\\women\\images-1661734566165.jpg",
                size: 83622
            }
        ],
    },
    {
        name: "Off-white",
        category: "women",
        color: "camel",
        type: "dress",
        description: "Intarsia pencil skirt",
        price: 689,
        size: ["XS", " S", " M", " L", " XL"],
        highlights: ["Camel", " Cotton blend", " Stretch design", " Patterned intarsia knit", " Signature arrows motif", " Ribbed waistband", " "],
        detail: "Irreverent brand Off-White puts a streetwear spin on a classic pencil silhouette, by adorning this pencil midi skirt with an all-over intarsia pattern of its signature Arrows logo. A contrasting neon-pink hem adds an extra distinctive touch, in tune with the label's creative aesthetic.",
        image: [{
                fieldname: "images",
                originalname: "off-white-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734828817.jpg",
                path: "public\\women\\images-1661734828817.jpg",
                size: 193280
            },
            {
                fieldname: "images",
                originalname: "off-white-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734828878.jpg",
                path: "public\\women\\images-1661734828878.jpg",
                size: 61150
            },
            {
                fieldname: "images",
                originalname: "off-white-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734828910.jpg",
                path: "public\\women\\images-1661734828910.jpg",
                size: 66598
            },
            {
                fieldname: "images",
                originalname: "off-white-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661734828910.jpg",
                path: "public\\women\\images-1661734828910.jpg",
                size: 135676
            }
        ],
    },
    {
        name: "Mugler",
        category: "women",
        color: "brown",
        type: "dress",
        description: "Waist tailored trousers",
        price: 1077,
        size: ["XL", " L"],
        highlights: ["Brown", " Cut-out detailing", " Tailored design", " Adjustable waist strap", " Concealed front fastening", " Pleat detailing"],
        detail: "Mugler's AW22 collection includes this pair of straight-leg tailored trousers in a stone brown hue. True to the label's sculptural roots, the trousers feature a cut-out detail at the waist with an adjustable belt fastening.",
        image: [{
                fieldname: "images",
                originalname: "mugler-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661735021645.jpg",
                path: "public\\women\\images-1661735021645.jpg",
                size: 19218
            },
            {
                fieldname: "images",
                originalname: "mugler-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661735021727.jpg",
                path: "public\\women\\images-1661735021727.jpg",
                size: 33190
            },
            {
                fieldname: "images",
                originalname: "mugler-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661735021871.jpg",
                path: "public\\women\\images-1661735021871.jpg",
                size: 38366
            },
            {
                fieldname: "images",
                originalname: "mugler-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661735022020.jpg",
                path: "public\\women\\images-1661735022020.jpg",
                size: 112282
            }
        ],
    },
    {
        name: "Jacquemus",
        category: "women",
        color: "black",
        type: "dress",
        description: "Robe Hielo dress",
        price: 407,
        size: ["XS", " S", " M", " L", " XL"],
        highlights: ["Black", " Stretch wool", " Cut-out detailing", " Contrast detailing", " Signature arrows motif", " Ribbed waistband"],
        detail: "Simon Porte Jacquemus delivers innovative style with a timeless appeal. This wool-blend halterneck dress is given an alternative finish through contrast stitching, cut-outs and asymmetric details.",
        image: [{
                fieldname: "images",
                originalname: "j-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661735640671.jpg",
                path: "public\\women\\images-1661735640671.jpg",
                size: 12772
            },
            {
                fieldname: "images",
                originalname: "jacquemus-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661735640672.jpg",
                path: "public\\women\\images-1661735640672.jpg",
                size: 32058
            },
            {
                fieldname: "images",
                originalname: "jacquemus-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/women",
                filename: "images-1661735640672.jpg",
                path: "public\\women\\images-1661735640672.jpg",
                size: 29422
            }
        ],
    },
    {
        name: "Stella Kids",
        category: "kids",
        color: "black",
        type: "dress",
        description: "Drawstring cargo track pants",
        price: 878,
        size: ["2yrs", " 3yrs", " 4yrs", " 5yrs", " 6yrs"],
        highlights: ["Black", " Cotton", " Elasticated drawstring waistband", " Two side cargo pockets", " Two diagonal pockets to the sides"],
        detail: "Drawstring cargo track pants",
        image: [{
                fieldname: "images",
                originalname: "stella-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736021736.jpg",
                path: "public\\kids\\images-1661736021736.jpg",
                size: 11674
            },
            {
                fieldname: "images",
                originalname: "stella-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736021737.jpg",
                path: "public\\kids\\images-1661736021737.jpg",
                size: 13890
            },
            {
                fieldname: "images",
                originalname: "stella-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736021737.jpg",
                path: "public\\kids\\images-1661736021737.jpg",
                size: 97757
            }
        ],
    },
    {
        name: "Molo",
        category: "kids",
        color: "black",
        type: "dress",
        description: "Teen denim skirt",
        price: 91,
        size: ["14yrs", " 16yrs"],
        highlights: ["Indigo blue", " Cotton blend", " Logo patch to the rear", " Belt loops", " Front button fastening"],
        detail: "Teen denim skirt. Cotton 72%, Recycled Polyester 27%, Elastane 1%",
        image: [{
                fieldname: "images",
                originalname: "molo-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736457211.jpg",
                path: "public\\kids\\images-1661736457211.jpg",
                size: 149094
            },
            {
                fieldname: "images",
                originalname: "molo-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736457387.jpg",
                path: "public\\kids\\images-1661736457387.jpg",
                size: 147495
            },
            {
                fieldname: "images",
                originalname: "molo-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736457389.jpg",
                path: "public\\kids\\images-1661736457389.jpg",
                size: 327062
            }
        ],
    },
    {
        name: "Adidas Yeezy",
        category: "kids",
        color: "#516E04",
        type: "shoes",
        description: "Foam runner sneakers",
        price: 227,
        size: ["14yrs", " 16yrs"],
        highlights: ["Foam rubber", " Perforated design", " Slip-on style", " Alimond toe", " Rubber sole"],
        detail: "The adidas YEEZY Kids Foam Runner arrives in an Stone Sage colour scheme. Designed by musical artist and creative Ye, this shoe first debuted on the soles of his daughter North West in 2019. They're known for their futuristic design and lightweight construction - which consists of EVA foam and harvested algae.",
        image: [{
                fieldname: "images",
                originalname: "adidas-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736921199.jpg",
                path: "public\\kids\\images-1661736921199.jpg",
                size: 46290
            },
            {
                fieldname: "images",
                originalname: "adidas-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736921199.jpg",
                path: "public\\kids\\images-1661736921199.jpg",
                size: 43170
            },
            {
                fieldname: "images",
                originalname: "adidas-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736921200.jpg",
                path: "public\\kids\\images-1661736921200.jpg",
                size: 46052
            },
            {
                fieldname: "images",
                originalname: "adidas-5.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661736921202.jpg",
                path: "public\\kids\\images-1661736921202.jpg",
                size: 51168
            }
        ],
    },
    {
        name: "Stella Kids",
        category: "kids",
        color: "black",
        type: "dress",
        description: "Color-block coat",
        price: 189,
        size: ["14yrs", " 16yrs"],
        highlights: ["Black/multicolor", " Recycled polyester", " Color-block paneled design", " Classic hood", " Front button fastening", " Two zip-fastening pockets "],
        detail: "Color-block coat",
        image: [{
                fieldname: "images",
                originalname: "stellaMc-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661737353733.jpg",
                path: "public\\kids\\images-1661737353733.jpg",
                size: 45516
            },
            {
                fieldname: "images",
                originalname: "stellaMc-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661737353734.jpg",
                path: "public\\kids\\images-1661737353734.jpg",
                size: 28138
            },
            {
                fieldname: "images",
                originalname: "stellaMc-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661737353736.jpg",
                path: "public\\kids\\images-1661737353736.jpg",
                size: 48292
            }
        ],
    },
    {
        name: "Bobo Choses",
        category: "kids",
        color: "brown",
        type: "dress",
        description: "Crew-neck sweatshirt",
        price: 67,
        size: ["14yrs", " 16yrs"],
        highlights: ["Beige", "Cotton", "Graphic print tothe front", "Logo print to the front", "Crew neck"],
        detail: "Long sleeves",
        image: [{
                fieldname: "images",
                originalname: "bobo-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661782291990.jpg",
                path: "public\\kids\\images-1661782291990.jpg",
                size: 57038
            },
            {
                fieldname: "images",
                originalname: "bobo-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661782291991.jpg",
                path: "public\\kids\\images-1661782291991.jpg",
                size: 41412
            },
            {
                fieldname: "images",
                originalname: "bobo-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661782291992.jpg",
                path: "public\\kids\\images-1661782291992.jpg",
                size: 259726
            }
        ],
    },
    {
        name: "Stella Kids",
        category: "kids",
        color: "brown",
        type: "shoes",
        description: "Color-block boots",
        price: 189,
        size: ["14yrs", " 16yrs"],
        highlights: ["Multicolor", " Color-block paneled design", " Front lace-up fastening", " Long pull-tab at the heel ", " Ankle length", " Round toe"],
        detail: "Color-block lace-up boots",
        image: [{
                fieldname: "images",
                originalname: "stellaMc1-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661782735745.jpg",
                path: "public\\kids\\images-1661782735745.jpg",
                size: 63048
            },
            {
                fieldname: "images",
                originalname: "stellaMc1-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661782735746.jpg",
                path: "public\\kids\\images-1661782735746.jpg",
                size: 47620
            },
            {
                fieldname: "images",
                originalname: "stellaMc1-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661782735747.jpg",
                path: "public\\kids\\images-1661782735747.jpg",
                size: 112840
            }
        ],
    },
    {
        name: "Mini Rodini",
        category: "kids",
        color: "brown",
        type: "bag",
        description: "Penguin-print backpack",
        price: 54,
        size: ["14yrs", " 16yrs"],
        highlights: ["Light brown", " All-over penguin print", " Embroidered logo to the front", " Single flat top handle", " Front zip fastening"],
        detail: "All over Penguin-print backpack",
        image: [{
                fieldname: "images",
                originalname: "rodini-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783079519.jpg",
                path: "public\\kids\\images-1661783079519.jpg",
                size: 147915
            },
            {
                fieldname: "images",
                originalname: "rodini-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783079523.jpg",
                path: "public\\kids\\images-1661783079523.jpg",
                size: 133589
            },
            {
                fieldname: "images",
                originalname: "rodini-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783079526.jpg",
                path: "public\\kids\\images-1661783079526.jpg",
                size: 150192
            },
            {
                fieldname: "images",
                originalname: "rodini-4.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783079636.jpg",
                path: "public\\kids\\images-1661783079636.jpg",
                size: 118670
            },
            {
                fieldname: "images",
                originalname: "rodini-5.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783079638.jpg",
                path: "public\\kids\\images-1661783079638.jpg",
                size: 150192
            }
        ],
    },
    {
        name: "VEJA Kids",
        category: "kids",
        color: "#264C0E",
        type: "shoes",
        description: "Nautico suede sneakers",
        price: 96,
        size: ["14yrs", " 16yrs"],
        highlights: ["Olive green", " Calf suede", " Logo patch to the side", " Logo patch at the tounge", " Round toe", " Front touch-strap fastening"],
        detail: "Nautico suede sneakers",
        image: [{
                fieldname: "images",
                originalname: "veja-1.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783286536.jpg",
                path: "public\\kids\\images-1661783286536.jpg",
                size: 81799
            },
            {
                fieldname: "images",
                originalname: "veja-2.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783286537.jpg",
                path: "public\\kids\\images-1661783286537.jpg",
                size: 57838
            },
            {
                fieldname: "images",
                originalname: "veja-3.jpg",
                encoding: "7bit",
                mimetype: "image/jpeg",
                destination: "./public/kids",
                filename: "images-1661783286538.jpg",
                path: "public\\kids\\images-1661783286538.jpg",
                size: 111178
            }
        ],
    }
]

export default itemsCollection;